### ISSUE TITLE
The-Receptionist

### ISSUE THREAD

**Issue by martin123456** [3D-I/The-Receptionist#1]
The-Receptionist wants paying

**Comment by 3D-I** [comment]
Is it a feature request or what?

**Comment by martin123456** [comment]
Think its a bug i installed it and used an old account to login but The-Receptionist wants paying before she will post any thing.

**Comment by 3D-I** [comment]
There is nothing in this repository, not yet. No code to be installed, what are you talking about?

Maybe you found the wrong repository, this one has been created yesterday and is empty.

**Comment by 3D-I** [comment]
No discussion value. Closing.

**Comment by Galixte** [comment]
Martin is a little funny, completely absurd this question… Maybe he’s the Martin from here: http://www.dmzx-web.net/memberlist.php?mode=viewprofile&u=90 
He is accustomed to paying for extensions, DMZX logic ^^

**Comment by martin123456** [comment]
He is accustomed to paying for extensions lol only ext's i have paid for is mchat related and thats just for my personnel uses.

This topic is a joke but i guess uk humour dont reach out side the uk.

**Comment by 3D-I** [comment]
Gentlemen, please use another place for this kind of discussions/jokes.
Don't let me me make this repo as a private one because of that.

Thanks for your comprehension, no need to reply.
