### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by Galixte** [3D-I/The-Receptionist#2]
Hi @3D-I,

i saw your topic, here: https://www.phpbb.com/community/viewtopic.php?f=456&t=2412451 but any idea when the first release will be available ? :)

**Comment by 3D-I** [comment]
There is another topic at my Board as well. ;)
https://3di.space/32/viewtopic.php?f=4&t=32

With 2 places where to ask things not related to **Issues/Bug**s reports I don't see the reason why using this place, sorry. Btw, everything is very well explained there.
